In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv("C:/Users/anish/Downloads/archive1/H1N1_Flu_Vaccines.csv")

In [3]:
df.head(2)

respondent_id  h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0              0           1.0             0.0                        0.0   
1              1           3.0             2.0                        0.0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   0.0                   0.0                    0.0   
1                   1.0                   0.0                    1.0   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          0.0                      1.0   
1                          0.0                      1.0   

   behavioral_touch_face  ...  rent_or_own   employment_status  \
0                    1.0  ...          Own  Not in Labor Force   
1                    1.0  ...         Rent            Employed   

   hhs_geo_region                census_msa  household_adults  \
0        oxchjgsf                   Non-MSA               0.0   
1        bhuqouqj  MSA, Not Principle  City               0.0   

   household_children  employment_industry  employment_occupation  \
0                 0.0                  NaN                    NaN   
1                 0.0             pxcmvdjn               xgwztkwe   

   h1n1_vaccine  seasonal_vaccine  
0             0                 0  
1             0                 1  

[2 rows x 38 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   respondent_id                26707 non-null  int64  
 1   h1n1_concern                 26615 non-null  float64
 2   h1n1_knowledge               26591 non-null  float64
 3   behavioral_antiviral_meds    26636 non-null  float64
 4   behavioral_avoidance         26499 non-null  float64
 5   behavioral_face_mask         26688 non-null  float64
 6   behavioral_wash_hands        26665 non-null  float64
 7   behavioral_large_gatherings  26620 non-null  float64
 8   behavioral_outside_home      26625 non-null  float64
 9   behavioral_touch_face        26579 non-null  float64
 10  doctor_recc_h1n1             24547 non-null  float64
 11  doctor_recc_seasonal         24547 non-null  float64
 12  chronic_med_condition        25736 non-null  float64
 13  child_under_6_mo

In [5]:
df.isnull().sum()

respondent_id                      0
h1n1_concern                      92
h1n1_knowledge                   116
behavioral_antiviral_meds         71
behavioral_avoidance             208
behavioral_face_mask              19
behavioral_wash_hands             42
behavioral_large_gatherings       87
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_h1n1                2160
doctor_recc_seasonal            2160
chronic_med_condition            971
child_under_6_months             820
health_worker                    804
health_insurance               12274
opinion_h1n1_vacc_effective      391
opinion_h1n1_risk                388
opinion_h1n1_sick_from_vacc      395
opinion_seas_vacc_effective      462
opinion_seas_risk                514
opinion_seas_sick_from_vacc      537
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4423
m

## Feature 1

In [6]:
df.drop("respondent_id",axis=1,inplace=True)

## Feature 2

In [7]:
df['h1n1_concern'].unique()

array([ 1.,  3.,  2.,  0., nan])

In [8]:
df['h1n1_concern']=df['h1n1_concern'].fillna(df['h1n1_concern'].mode()[0])

In [9]:
df['h1n1_concern']=df['h1n1_concern'].astype(int)

In [10]:
df['h1n1_concern'].unique()

array([1, 3, 2, 0])

## Feature 3

In [11]:
df['h1n1_knowledge'].unique()

array([ 0.,  2.,  1., nan])

In [12]:
df['h1n1_knowledge']=df['h1n1_knowledge'].fillna(df['h1n1_knowledge'].mode()[0])

In [13]:
df['h1n1_knowledge']=df['h1n1_knowledge'].astype(int)

In [14]:
df['h1n1_knowledge'].unique()

array([0, 2, 1])

## Feature 4

In [15]:
df['behavioral_antiviral_meds'].unique()

array([ 0.,  1., nan])

In [16]:
df['behavioral_antiviral_meds']=df['behavioral_antiviral_meds'].fillna(df['behavioral_antiviral_meds'].mode()[0])

In [17]:
df['behavioral_antiviral_meds']=df['behavioral_antiviral_meds'].astype(int)

In [18]:
df['behavioral_antiviral_meds'].unique()

array([0, 1])

## Feature 5

In [19]:
df['behavioral_avoidance'].unique()

array([ 0.,  1., nan])

In [20]:
df['behavioral_avoidance']=df['behavioral_avoidance'].fillna(df['behavioral_avoidance'].mode()[0])

In [21]:
df['behavioral_avoidance']=df['behavioral_avoidance'].astype(int)

In [22]:
df['behavioral_avoidance'].unique()

array([0, 1])

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   h1n1_concern                 26707 non-null  int32  
 1   h1n1_knowledge               26707 non-null  int32  
 2   behavioral_antiviral_meds    26707 non-null  int32  
 3   behavioral_avoidance         26707 non-null  int32  
 4   behavioral_face_mask         26688 non-null  float64
 5   behavioral_wash_hands        26665 non-null  float64
 6   behavioral_large_gatherings  26620 non-null  float64
 7   behavioral_outside_home      26625 non-null  float64
 8   behavioral_touch_face        26579 non-null  float64
 9   doctor_recc_h1n1             24547 non-null  float64
 10  doctor_recc_seasonal         24547 non-null  float64
 11  chronic_med_condition        25736 non-null  float64
 12  child_under_6_months         25887 non-null  float64
 13  health_worker   

## Feature 6

In [24]:
df['behavioral_face_mask'].unique()

array([ 0.,  1., nan])

In [25]:
df['behavioral_face_mask']=df['behavioral_face_mask'].fillna(df['behavioral_face_mask'].mode()[0])

In [26]:
df['behavioral_face_mask']=df['behavioral_face_mask'].astype(int)

In [27]:
df['behavioral_face_mask'].unique()

array([0, 1])

## Feature 7

In [28]:
df['behavioral_wash_hands'].unique()

array([ 0.,  1., nan])

In [29]:
df['behavioral_wash_hands']=df['behavioral_wash_hands'].fillna(df['behavioral_wash_hands'].mode()[0])

In [30]:
df['behavioral_wash_hands']=df['behavioral_wash_hands'].astype(int)

In [31]:
df['behavioral_wash_hands'].unique()

array([0, 1])

In [32]:
df.head(2)

h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0             1               0                          0   
1             3               2                          0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                     0                     0                      0   
1                     1                     0                      1   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          0.0                      1.0   
1                          0.0                      1.0   

   behavioral_touch_face  doctor_recc_h1n1  ...  rent_or_own  \
0                    1.0               0.0  ...          Own   
1                    1.0               0.0  ...         Rent   

    employment_status  hhs_geo_region                census_msa  \
0  Not in Labor Force        oxchjgsf                   Non-MSA   
1            Employed        bhuqouqj  MSA, Not Principle  City   

   household_adults  household_children  employment_industry  \
0               0.0                 0.0                  NaN   
1               0.0                 0.0             pxcmvdjn   

   employment_occupation  h1n1_vaccine  seasonal_vaccine  
0                    NaN             0                 0  
1               xgwztkwe             0                 1  

[2 rows x 37 columns]

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   h1n1_concern                 26707 non-null  int32  
 1   h1n1_knowledge               26707 non-null  int32  
 2   behavioral_antiviral_meds    26707 non-null  int32  
 3   behavioral_avoidance         26707 non-null  int32  
 4   behavioral_face_mask         26707 non-null  int32  
 5   behavioral_wash_hands        26707 non-null  int32  
 6   behavioral_large_gatherings  26620 non-null  float64
 7   behavioral_outside_home      26625 non-null  float64
 8   behavioral_touch_face        26579 non-null  float64
 9   doctor_recc_h1n1             24547 non-null  float64
 10  doctor_recc_seasonal         24547 non-null  float64
 11  chronic_med_condition        25736 non-null  float64
 12  child_under_6_months         25887 non-null  float64
 13  health_worker   

## Feature 8

In [34]:
df['behavioral_large_gatherings'].unique()

array([ 0.,  1., nan])

In [35]:
df['behavioral_large_gatherings']=df['behavioral_large_gatherings'].fillna(df['behavioral_large_gatherings'].mode()[0])

In [36]:
df['behavioral_large_gatherings']=df['behavioral_large_gatherings'].astype(int)

In [37]:
df['behavioral_large_gatherings'].unique()

array([0, 1])

## Feature 9

In [38]:
df['behavioral_outside_home'].unique()

array([ 1.,  0., nan])

In [40]:
df['behavioral_outside_home']=df['behavioral_outside_home'].fillna(df['behavioral_outside_home'].mode()[0])

In [41]:
df['behavioral_outside_home']=df['behavioral_outside_home'].astype(int)

In [42]:
df['behavioral_outside_home'].unique()

array([1, 0])

## Feature 10

In [43]:
df['behavioral_touch_face'].unique()

array([ 1.,  0., nan])

In [44]:
df['behavioral_touch_face']=df['behavioral_touch_face'].fillna(df['behavioral_touch_face'].mode()[0])

In [45]:
df['behavioral_touch_face']=df['behavioral_touch_face'].astype(int)

In [46]:
df['behavioral_touch_face'].unique()

array([1, 0])

## Feature 11

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   h1n1_concern                 26707 non-null  int32  
 1   h1n1_knowledge               26707 non-null  int32  
 2   behavioral_antiviral_meds    26707 non-null  int32  
 3   behavioral_avoidance         26707 non-null  int32  
 4   behavioral_face_mask         26707 non-null  int32  
 5   behavioral_wash_hands        26707 non-null  int32  
 6   behavioral_large_gatherings  26707 non-null  int32  
 7   behavioral_outside_home      26707 non-null  int32  
 8   behavioral_touch_face        26707 non-null  int32  
 9   doctor_recc_h1n1             24547 non-null  float64
 10  doctor_recc_seasonal         24547 non-null  float64
 11  chronic_med_condition        25736 non-null  float64
 12  child_under_6_months         25887 non-null  float64
 13  health_worker   

In [48]:
df.head(2)

h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0             1               0                          0   
1             3               2                          0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                     0                     0                      0   
1                     1                     0                      1   

   behavioral_large_gatherings  behavioral_outside_home  \
0                            0                        1   
1                            0                        1   

   behavioral_touch_face  doctor_recc_h1n1  ...  rent_or_own  \
0                      1               0.0  ...          Own   
1                      1               0.0  ...         Rent   

    employment_status  hhs_geo_region                census_msa  \
0  Not in Labor Force        oxchjgsf                   Non-MSA   
1            Employed        bhuqouqj  MSA, Not Principle  City   

   household_adults  household_children  employment_industry  \
0               0.0                 0.0                  NaN   
1               0.0                 0.0             pxcmvdjn   

   employment_occupation  h1n1_vaccine  seasonal_vaccine  
0                    NaN             0                 0  
1               xgwztkwe             0                 1  

[2 rows x 37 columns]

In [49]:
df['doctor_recc_h1n1'].unique()

array([ 0., nan,  1.])

In [50]:
df['doctor_recc_h1n1']=df['doctor_recc_h1n1'].fillna(df['doctor_recc_h1n1'].mode()[0])

In [51]:
df['doctor_recc_h1n1']=df['doctor_recc_h1n1'].astype(int)

In [52]:
df['doctor_recc_h1n1'].unique()

array([0, 1])

## Feature 12

In [53]:
df['doctor_recc_seasonal'].unique()

array([ 0., nan,  1.])

In [54]:
df['doctor_recc_seasonal']=df['doctor_recc_seasonal'].fillna(df['doctor_recc_seasonal'].mode()[0])

In [55]:
df['doctor_recc_seasonal']=df['doctor_recc_seasonal'].astype(int)

In [56]:
df['doctor_recc_seasonal'].unique()

array([0, 1])

## Feature 13

In [57]:
df['chronic_med_condition'].unique()

array([ 0.,  1., nan])

In [58]:
df['chronic_med_condition']=df['chronic_med_condition'].fillna(df['chronic_med_condition'].mode()[0])

In [59]:
df['chronic_med_condition']=df['chronic_med_condition'].astype(int)

In [60]:
df['chronic_med_condition'].unique()

array([0, 1])

## Feature 14

In [61]:
df['child_under_6_months'].unique()

array([ 0.,  1., nan])

In [62]:
df['child_under_6_months']=df['child_under_6_months'].fillna(df['child_under_6_months'].mode()[0])

In [63]:
df['child_under_6_months']=df['child_under_6_months'].astype(int)

In [64]:
df['child_under_6_months'].unique()

array([0, 1])

## Feature 15

In [65]:
df['health_worker'].unique()

array([ 0.,  1., nan])

In [66]:
df['health_worker']=df['health_worker'].fillna(df['health_worker'].mode()[0])

In [67]:
df['health_worker']=df['health_worker'].astype(int)

In [68]:
df['health_worker'].unique()

array([0, 1])

## Feature 16

In [69]:
df['health_insurance'].unique()

array([ 1., nan,  0.])

In [70]:
df['health_insurance']=df['health_insurance'].fillna(df['health_insurance'].mode()[0])

In [71]:
df['health_insurance']=df['health_insurance'].astype(int)

In [72]:
df['health_insurance'].unique()

array([1, 0])

## Feature 17

In [73]:
df['opinion_h1n1_vacc_effective'].unique()

array([ 3.,  5.,  4.,  2.,  1., nan])

In [74]:
df['opinion_h1n1_vacc_effective']=df['opinion_h1n1_vacc_effective'].fillna(df['opinion_h1n1_vacc_effective'].mode()[0])

In [75]:
df['opinion_h1n1_vacc_effective']=df['opinion_h1n1_vacc_effective'].astype(int)

In [76]:
df['opinion_h1n1_vacc_effective'].unique()

array([3, 5, 4, 2, 1])

## Feature 18

In [78]:
df['opinion_h1n1_risk'].unique()

array([ 1.,  4.,  3.,  2.,  5., nan])

In [79]:
df['opinion_h1n1_risk']=df['opinion_h1n1_risk'].fillna(df['opinion_h1n1_risk'].mode()[0])

In [80]:
df['opinion_h1n1_risk']=df['opinion_h1n1_risk'].astype(int)

In [81]:
df['opinion_h1n1_risk'].unique()

array([1, 4, 3, 2, 5])

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   h1n1_concern                 26707 non-null  int32  
 1   h1n1_knowledge               26707 non-null  int32  
 2   behavioral_antiviral_meds    26707 non-null  int32  
 3   behavioral_avoidance         26707 non-null  int32  
 4   behavioral_face_mask         26707 non-null  int32  
 5   behavioral_wash_hands        26707 non-null  int32  
 6   behavioral_large_gatherings  26707 non-null  int32  
 7   behavioral_outside_home      26707 non-null  int32  
 8   behavioral_touch_face        26707 non-null  int32  
 9   doctor_recc_h1n1             26707 non-null  int32  
 10  doctor_recc_seasonal         26707 non-null  int32  
 11  chronic_med_condition        26707 non-null  int32  
 12  child_under_6_months         26707 non-null  int32  
 13  health_worker   

## Feature 19

In [83]:
df['opinion_h1n1_sick_from_vacc'].unique()

array([ 2.,  4.,  1.,  5.,  3., nan])

In [84]:
df['opinion_h1n1_sick_from_vacc']=df['opinion_h1n1_sick_from_vacc'].fillna(df['opinion_h1n1_sick_from_vacc'].mode()[0])

In [85]:
df['opinion_h1n1_sick_from_vacc']=df['opinion_h1n1_sick_from_vacc'].astype(int)

In [86]:
df['opinion_h1n1_sick_from_vacc'].unique()

array([2, 4, 1, 5, 3])

## Feature 20

In [87]:
df['opinion_seas_vacc_effective'].unique()

array([ 2.,  4.,  5.,  3.,  1., nan])

In [88]:
df['opinion_seas_vacc_effective']=df['opinion_seas_vacc_effective'].fillna(df['opinion_seas_vacc_effective'].mode()[0])

In [89]:
df['opinion_seas_vacc_effective']=df['opinion_seas_vacc_effective'].astype(int)

In [90]:
df['opinion_seas_vacc_effective'].unique()

array([2, 4, 5, 3, 1])

## Featurev 21

In [91]:
df['opinion_seas_risk'].unique()

array([ 1.,  2.,  4.,  3.,  5., nan])

In [92]:
df['opinion_seas_risk']=df['opinion_seas_risk'].fillna(df['opinion_seas_risk'].mode()[0])

In [93]:
df['opinion_seas_risk']=df['opinion_seas_risk'].astype(int)

In [94]:
df['opinion_seas_risk'].unique()

array([1, 2, 4, 3, 5])

## Feature 22

In [95]:
df['opinion_seas_sick_from_vacc'].unique()

array([ 2.,  4.,  1.,  5., nan,  3.])

In [96]:
df['opinion_seas_sick_from_vacc']=df['opinion_seas_sick_from_vacc'].fillna(df['opinion_seas_sick_from_vacc'].mode()[0])

In [97]:
df['opinion_seas_sick_from_vacc']=df['opinion_seas_sick_from_vacc'].astype(int)

In [98]:
df['opinion_seas_sick_from_vacc'].unique()

array([2, 4, 1, 5, 3])

## Feature 23

In [100]:
df['age_group'].unique()

array(['55 - 64 Years', '35 - 44 Years', '18 - 34 Years', '65+ Years',
       '45 - 54 Years'], dtype=object)

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   h1n1_concern                 26707 non-null  int32  
 1   h1n1_knowledge               26707 non-null  int32  
 2   behavioral_antiviral_meds    26707 non-null  int32  
 3   behavioral_avoidance         26707 non-null  int32  
 4   behavioral_face_mask         26707 non-null  int32  
 5   behavioral_wash_hands        26707 non-null  int32  
 6   behavioral_large_gatherings  26707 non-null  int32  
 7   behavioral_outside_home      26707 non-null  int32  
 8   behavioral_touch_face        26707 non-null  int32  
 9   doctor_recc_h1n1             26707 non-null  int32  
 10  doctor_recc_seasonal         26707 non-null  int32  
 11  chronic_med_condition        26707 non-null  int32  
 12  child_under_6_months         26707 non-null  int32  
 13  health_worker   

In [102]:
df.isnull().sum()

h1n1_concern                       0
h1n1_knowledge                     0
behavioral_antiviral_meds          0
behavioral_avoidance               0
behavioral_face_mask               0
behavioral_wash_hands              0
behavioral_large_gatherings        0
behavioral_outside_home            0
behavioral_touch_face              0
doctor_recc_h1n1                   0
doctor_recc_seasonal               0
chronic_med_condition              0
child_under_6_months               0
health_worker                      0
health_insurance                   0
opinion_h1n1_vacc_effective        0
opinion_h1n1_risk                  0
opinion_h1n1_sick_from_vacc        0
opinion_seas_vacc_effective        0
opinion_seas_risk                  0
opinion_seas_sick_from_vacc        0
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4423
marital_status                  1408
r

In [103]:
df['age_group']=df['age_group'].map({'18 - 34 Years':0, '35 - 44 Years':1,'45 - 54 Years':2,'55 - 64 Years':3,'65+ Years':4})


In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   h1n1_concern                 26707 non-null  int32  
 1   h1n1_knowledge               26707 non-null  int32  
 2   behavioral_antiviral_meds    26707 non-null  int32  
 3   behavioral_avoidance         26707 non-null  int32  
 4   behavioral_face_mask         26707 non-null  int32  
 5   behavioral_wash_hands        26707 non-null  int32  
 6   behavioral_large_gatherings  26707 non-null  int32  
 7   behavioral_outside_home      26707 non-null  int32  
 8   behavioral_touch_face        26707 non-null  int32  
 9   doctor_recc_h1n1             26707 non-null  int32  
 10  doctor_recc_seasonal         26707 non-null  int32  
 11  chronic_med_condition        26707 non-null  int32  
 12  child_under_6_months         26707 non-null  int32  
 13  health_worker   

## Feature 24

In [105]:
df['education'].unique()

array(['< 12 Years', '12 Years', 'College Graduate', 'Some College', nan],
      dtype=object)

In [106]:
df['education']=df['education'].fillna(df['education'].mode()[0])

In [107]:
#label encoding

from sklearn.preprocessing import LabelEncoder

labelencoder=LabelEncoder()
df["education"]=labelencoder.fit_transform(df["education"])

In [108]:
df['education'].unique()

array([1, 0, 2, 3])

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   h1n1_concern                 26707 non-null  int32  
 1   h1n1_knowledge               26707 non-null  int32  
 2   behavioral_antiviral_meds    26707 non-null  int32  
 3   behavioral_avoidance         26707 non-null  int32  
 4   behavioral_face_mask         26707 non-null  int32  
 5   behavioral_wash_hands        26707 non-null  int32  
 6   behavioral_large_gatherings  26707 non-null  int32  
 7   behavioral_outside_home      26707 non-null  int32  
 8   behavioral_touch_face        26707 non-null  int32  
 9   doctor_recc_h1n1             26707 non-null  int32  
 10  doctor_recc_seasonal         26707 non-null  int32  
 11  chronic_med_condition        26707 non-null  int32  
 12  child_under_6_months         26707 non-null  int32  
 13  health_worker   

## Feature 25

In [110]:
df['race'].unique()

array(['White', 'Black', 'Other or Multiple', 'Hispanic'], dtype=object)

In [111]:
df["race"]=labelencoder.fit_transform(df["race"])

In [112]:
df['race'].unique()

array([3, 0, 2, 1])

## Feature 26

In [113]:
df["sex"]=labelencoder.fit_transform(df["sex"])

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   h1n1_concern                 26707 non-null  int32  
 1   h1n1_knowledge               26707 non-null  int32  
 2   behavioral_antiviral_meds    26707 non-null  int32  
 3   behavioral_avoidance         26707 non-null  int32  
 4   behavioral_face_mask         26707 non-null  int32  
 5   behavioral_wash_hands        26707 non-null  int32  
 6   behavioral_large_gatherings  26707 non-null  int32  
 7   behavioral_outside_home      26707 non-null  int32  
 8   behavioral_touch_face        26707 non-null  int32  
 9   doctor_recc_h1n1             26707 non-null  int32  
 10  doctor_recc_seasonal         26707 non-null  int32  
 11  chronic_med_condition        26707 non-null  int32  
 12  child_under_6_months         26707 non-null  int32  
 13  health_worker   

## Featutre 27

In [115]:
df['income_poverty'].unique()

array(['Below Poverty', '<= $75,000, Above Poverty', '> $75,000', nan],
      dtype=object)

In [116]:
df['income_poverty']=df['income_poverty'].fillna(df['income_poverty'].mode()[0])

In [117]:
df["income_poverty"]=labelencoder.fit_transform(df["income_poverty"])

## Feature 28

In [118]:
df['marital_status'].unique()

array(['Not Married', 'Married', nan], dtype=object)

In [119]:
df['marital_status']=df['marital_status'].fillna(df['marital_status'].mode()[0])

In [120]:
df["marital_status"]=labelencoder.fit_transform(df["marital_status"])

## Feature 29

In [121]:
df['rent_or_own'].unique()

array(['Own', 'Rent', nan], dtype=object)

In [122]:
df['rent_or_own']=df['rent_or_own'].fillna(df['rent_or_own'].mode()[0])

In [123]:
df["rent_or_own"]=labelencoder.fit_transform(df["rent_or_own"])

## Feature 29

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   h1n1_concern                 26707 non-null  int32  
 1   h1n1_knowledge               26707 non-null  int32  
 2   behavioral_antiviral_meds    26707 non-null  int32  
 3   behavioral_avoidance         26707 non-null  int32  
 4   behavioral_face_mask         26707 non-null  int32  
 5   behavioral_wash_hands        26707 non-null  int32  
 6   behavioral_large_gatherings  26707 non-null  int32  
 7   behavioral_outside_home      26707 non-null  int32  
 8   behavioral_touch_face        26707 non-null  int32  
 9   doctor_recc_h1n1             26707 non-null  int32  
 10  doctor_recc_seasonal         26707 non-null  int32  
 11  chronic_med_condition        26707 non-null  int32  
 12  child_under_6_months         26707 non-null  int32  
 13  health_worker   

In [125]:
df['employment_status'].unique()

array(['Not in Labor Force', 'Employed', 'Unemployed', nan], dtype=object)

In [126]:
df['employment_status']=df['employment_status'].fillna(df['employment_status'].mode()[0])

In [127]:
df["employment_status"]=labelencoder.fit_transform(df["employment_status"])

## Feature 30

In [128]:
df['hhs_geo_region'].unique()

array(['oxchjgsf', 'bhuqouqj', 'qufhixun', 'lrircsnp', 'atmpeygn',
       'lzgpxyit', 'fpwskwrf', 'mlyzmhmf', 'dqpwygqj', 'kbazzjca'],
      dtype=object)

In [129]:
df["hhs_geo_region"]=labelencoder.fit_transform(df["hhs_geo_region"])

## Feature 31

In [130]:
df['census_msa'].unique()

array(['Non-MSA', 'MSA, Not Principle  City', 'MSA, Principle City'],
      dtype=object)

In [131]:
df["census_msa"]=labelencoder.fit_transform(df["census_msa"])

## Feature 32

In [132]:
df['household_adults'].unique()

array([ 0.,  2.,  1.,  3., nan])

In [133]:
df['household_adults']=df['household_adults'].fillna(df['household_adults'].mode()[0])

In [134]:
df['household_adults']=df['household_adults'].astype(int)

In [135]:
df['household_adults'].unique()

array([0, 2, 1, 3])

## Feature 33

In [136]:
df['household_children'].unique()

array([ 0.,  3.,  2.,  1., nan])

In [137]:
df['household_children']=df['household_children'].fillna(df['household_children'].mode()[0])

In [138]:
df['household_children']=df['household_children'].astype(int)

In [139]:
df['household_children'].unique()

array([0, 3, 2, 1])

## Feature 34

In [140]:
df['employment_industry'].unique()

array([nan, 'pxcmvdjn', 'rucpziij', 'wxleyezf', 'saaquncn', 'xicduogh',
       'ldnlellj', 'wlfvacwt', 'nduyfdeo', 'fcxhlnwr', 'vjjrobsf',
       'arjwrbjb', 'atmlpfrs', 'msuufmds', 'xqicxuve', 'phxvnwax',
       'dotnnunm', 'mfikgejo', 'cfqqtusy', 'mcubkhph', 'haxffmxo',
       'qnlwzans'], dtype=object)

In [141]:
df["employment_industry"]=labelencoder.fit_transform(df["employment_industry"])

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   h1n1_concern                 26707 non-null  int32 
 1   h1n1_knowledge               26707 non-null  int32 
 2   behavioral_antiviral_meds    26707 non-null  int32 
 3   behavioral_avoidance         26707 non-null  int32 
 4   behavioral_face_mask         26707 non-null  int32 
 5   behavioral_wash_hands        26707 non-null  int32 
 6   behavioral_large_gatherings  26707 non-null  int32 
 7   behavioral_outside_home      26707 non-null  int32 
 8   behavioral_touch_face        26707 non-null  int32 
 9   doctor_recc_h1n1             26707 non-null  int32 
 10  doctor_recc_seasonal         26707 non-null  int32 
 11  chronic_med_condition        26707 non-null  int32 
 12  child_under_6_months         26707 non-null  int32 
 13  health_worker                26

## Feature 35

In [143]:
df['employment_occupation'].unique()

array([nan, 'xgwztkwe', 'xtkaffoo', 'emcorrxb', 'vlluhbov', 'xqwwgdyp',
       'ccgxvspp', 'qxajmpny', 'kldqjyjy', 'mxkfnird', 'hfxkjkmi',
       'bxpfxfdn', 'ukymxvdu', 'cmhcxjea', 'haliazsg', 'dlvbwzss',
       'xzmlyyjv', 'oijqvulv', 'rcertsgn', 'tfqavkke', 'hodpvpew',
       'uqqtjvyb', 'pvmttkik', 'dcjcmpih'], dtype=object)

In [144]:
df['employment_occupation']=df['employment_occupation'].fillna(df['employment_occupation'].mode()[0])

In [145]:
df["employment_occupation"]=labelencoder.fit_transform(df["employment_occupation"])

In [147]:
X=df.drop('h1n1_vaccine',axis=1)

In [149]:
y=df['h1n1_vaccine']

In [150]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [151]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

## Logistic Regression Model

In [152]:
from sklearn.linear_model import LogisticRegression
logModel=LogisticRegression(solver='lbfgs', max_iter=1000000,dual=False)

In [153]:
logModel.fit(X_train, y_train,)
predictions = logModel.predict(X_test)

In [154]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)*100

84.8763331064216

## Naive bayes Model

In [155]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
classifier= GaussianNB()
classifier.fit(X_train, y_train)
classifier.class_prior_

array([0.78729112, 0.21270888])

In [159]:
predicts=classifier.predict(X_test)
accuracy=round(accuracy_score(y_test,predicts),3)
print(accuracy*100)

78.60000000000001


## XGBoost Model

In [160]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_wine

In [161]:
model = XGBClassifier(eval_metric='mlogloss')

In [162]:
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='mlogloss', gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_to_onehot=4, max_delta_step=0, max_depth=6,
              max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=0,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [163]:
y_pred1 = model.predict(X_test)

In [165]:
accuracy = accuracy_score(y_test, y_pred1)
print(accuracy*100)

84.28636260494667


## SVM Model

In [166]:
from sklearn.svm import SVC  
clf = SVC(kernel='linear') 
  
# fitting x samples and y classes 
clf.fit(X_train, y_train) 

SVC(kernel='linear')

In [167]:
y_pred2=clf.predict(X_test)

In [168]:
accuracy = accuracy_score(y_test, y_pred2)
print(accuracy*100)

84.94440662582255


## Random Forest Model

In [169]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 100) 
 
# Training the model on the training dataset
# fit function is used to train the model using the training sets as parameters
clf.fit(X_train, y_train)
 
# performing predictions on the test dataset
y_pred = clf.predict(X_test)
 


In [175]:
# metrics are used to find accuracy or error
from sklearn import metrics 
print()
 
# using metrics module for accuracy calculation
print( metrics.accuracy_score(y_test, y_pred)*100)


84.53596550941683


## D-Tree Model

In [171]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [172]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred3 = clf.predict(X_test)

In [176]:
print(metrics.accuracy_score(y_test, y_pred3)*100)

77.79668708872248
