In [1]:
import numpy as np 

## use shift+tab for help 

In [2]:
a=[6,7,9,0]
np.array(a)

array([6, 7, 9, 0])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,30) #makes a array of (x,y) with elements starting from x to y-1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(5,30,5) #makes a array of (x,y) with elements starting from x to y-1 with every 5th element

array([ 5, 10, 15, 20, 25])

In [7]:
np.zeros(100)#makes a array of 0s in float data type

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(10,dtype=int)#makes a array of 0s in data type as mentioned and size as mentioned

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((2,5))#makes a matrix of size x*y with ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,1,5)#makes a array of 0 to 1 with 5 elements with equal distribution start and end number should be same

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [13]:
np.eye(10,dtype=int)#identity matrix of size n*n 

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [17]:
np.random.rand(2,4) #selecting random numbers of matrix x*y

array([[0.37508987, 0.37183445, 0.68943169, 0.07229109],
       [0.32516587, 0.51472549, 0.10399015, 0.19668571]])

In [15]:
np.random.randn(2,4) #selecting random numbers of matrix x*y from normal distribution

array([[-0.95591514,  1.31026964,  0.00419582,  1.38846762],
       [ 0.20715706, -0.36261998, -0.26628324,  0.80033029]])

In [18]:
np.random.randint(2,10) #random integers are seen from x to y

7

In [19]:
np.random.randint(20,56,100)#100 integers randomly selected between x to y

array([25, 39, 46, 33, 22, 51, 39, 23, 23, 38, 27, 49, 36, 29, 23, 32, 46,
       52, 42, 49, 40, 26, 39, 45, 48, 24, 42, 45, 25, 41, 29, 30, 22, 33,
       41, 35, 29, 47, 49, 42, 30, 20, 41, 39, 50, 38, 25, 34, 34, 20, 35,
       37, 34, 25, 40, 37, 48, 45, 31, 44, 33, 44, 20, 49, 39, 26, 55, 47,
       39, 46, 37, 49, 48, 25, 46, 21, 50, 24, 44, 34, 45, 41, 46, 54, 43,
       29, 55, 41, 36, 43, 26, 48, 39, 23, 44, 33, 50, 40, 27, 42])

In [20]:
sample_array=np.arange(30) #default starting value is 0 only
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
rand_array=np.random.randint(0,100,20)
rand_array

array([15, 47, 87, 82, 67, 30, 92, 96, 22, 53, 13, 56,  3, 30, 19, 70, 33,
        6, 77, 44])

In [22]:
sample_array.reshape(5,6) # to change matrix of 30*1 to 5*6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
rand_array.min()# To find the minimum most element in the array


3

In [26]:
rand_array.argmin()# To find the minimum most element in the array

12

In [28]:
sample_array.dtype#to find the data type in the array

dtype('int32')

In [33]:
a=np.random.rand(4,4)
a

array([[0.33830577, 0.51654237, 0.54934604, 0.90396285],
       [0.69504022, 0.13847345, 0.31796986, 0.94629568],
       [0.40182217, 0.44689192, 0.87492126, 0.70307377],
       [0.72866852, 0.62683163, 0.32853655, 0.24714483]])

In [34]:
a.T #To find the transpose of the matrix

array([[0.33830577, 0.69504022, 0.40182217, 0.72866852],
       [0.51654237, 0.13847345, 0.44689192, 0.62683163],
       [0.54934604, 0.31796986, 0.87492126, 0.32853655],
       [0.90396285, 0.94629568, 0.70307377, 0.24714483]])

In [35]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
sample_array[8]

18

In [37]:
sample_array[2:5]

array([12, 13, 14])

In [38]:
sample_array[2:5]=100
sample_array

array([ 10,  11, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [39]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([ 10,  11, 100, 100, 100,  15,  16])

In [40]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [41]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [42]:
sample_matrix[0][2]

1

In [43]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [44]:
sample_matrix[2]

array([56, 76, 24,  7])

In [45]:
sample_matrix=np.array(([30,10,1,23],[24,21,32,33],[6,76,24,7]))
sample_matrix

array([[30, 10,  1, 23],
       [24, 21, 32, 33],
       [ 6, 76, 24,  7]])

In [46]:
sample_matrix[:,(3,2)]#custom indexing

array([[23,  1],
       [33, 32],
       [ 7, 24]])

## selection techniques

In [47]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [50]:
bool=sample_array<10 #to see if elements in the array satisfies the condition
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [51]:
sample_array[bool]#only true elements will be coming now

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
sample_array+sample_array #(a[i]+b[i])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [53]:
np.exp(sample_array)#element wise exposential of x

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [54]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [55]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [56]:
np.max(sample_array)

30

In [57]:
np.min(sample_array)

1

In [58]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [59]:
np.std(sample_array)

8.65544144839919

In [60]:
np.var(sample_array)


74.91666666666667

In [61]:
np.mean(sample_array)

15.5

In [62]:
array=np.random.randn(3,6)
array

array([[-2.18602589,  0.14970245, -0.13650991,  1.22066728, -1.05673627,
         0.15842498],
       [-0.33761287, -0.33248035, -1.3627994 ,  0.61530899, -0.99954354,
         0.10831037],
       [ 0.88653748,  0.41465316, -0.37402624,  0.66400432, -1.21536147,
         0.42451689]])

In [63]:
np.round(array,decimals=2)

array([[-2.19,  0.15, -0.14,  1.22, -1.06,  0.16],
       [-0.34, -0.33, -1.36,  0.62, -1.  ,  0.11],
       [ 0.89,  0.41, -0.37,  0.66, -1.22,  0.42]])

In [64]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')